name: Build and deploy a container to an Azure Container Apps - ACA
#az ad sp create-for-rbac -n "github-actions-ci-cd" --role Contributor --scope /subscriptions/$SUBSCRIPTION_ID --sdk-auth

env:
  #IMAGE_NAME comes from: https://github.com/HoussemDellai/aca-course package
  #IMAGE_NAME: houssemdellai/containerapps-album-api
  IMAGE_NAME: RubenBZgz/containerapps-album-api
  CONTAINERAPPS_APP: album-backend-api
  CONTAINERAPPS_ENVIRONMENT: aca-environment
  RESOURCE_GROUP: rg-containerapps-github-actions

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push-container-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}


      # EL ERROR ESTÁ AQUÍ, FORBIDDEN. EL PUSH LO INTENTA SUBIR A LA CUENTA DE HOUSSEM DELLAI
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          #tags: user/app:latest
          file: ./backend_api/backend_api_csharp/Dockerfile
          context: ./backend_api/backend_api_csharp

  deploy-to-container-apps:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-push-container-image

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          registryUrl: ghcr.io
          imageToDeploy: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          targetPort: 3500
          ingress: external
          containerAppName: ${{ env.CONTAINERAPPS_APP }}
          containerAppEnvironment: ${{ env.CONTAINERAPPS_ENVIRONMENT }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
